### ISSUE TITLE
Default value and transformations

### ISSUE THREAD

**Issue by jzakrzewski** [CLIUtils/CLI11#330] opened 2019-10-07 19:18 UTC
I do this:
```c++
cmd->add_option("--existing", "What to do if deployment already exists in the destination")
      ->transform(CLI::CheckedTransformer(std::unordered_map<std::string, ExistingBehaviour>{
          {"abort"s, ExistingBehaviour::abort},
          {"overwrite"s, ExistingBehaviour ::overwrite},
          {"delete"s, ExistingBehaviour::remove},
          {"remove"s, ExistingBehaviour::remove}}))
      ->default_val("abort");
```
and all is well, the transformer runs but later (in a subcommand callback) I do:
```c++
cmd->get_option("--existing")->as<ExistingBehaviour>()
```
And it throws.
It turns out that, even though the transformer runs, the original default ("abort") is stored instead of (apparently expected) "0". If I actually provide "--existing=abort" on the command line, it works. I could just put "0" as default but then a) help is broken, b) if I change the enum the hell breaks loose.

It looks to me like this function is responsible:
https://github.com/CLIUtils/CLI11/blob/8ecce8fd2c49f64c80e5757cb12d2fd1fa62f242/include/CLI/Option.hpp#L973-L980

**Comment by phlptp** [comment] 2019-10-08 04:06
I think this is the same issue as #305.  The root cause is that the default values are not passed through the validators/transforms, and related to that the `as` function gets the default through a different mechanism.  I think PR #325 will be able to resolve this and several other issues once it is able to be merged, but we should add that use case as one of the tests to make sure.

**Comment by jzakrzewski** [comment] 2019-10-08 06:33
It didn't look the same for me but you understand the code much better, so I believe you ;)
I just observed that it's going through validation and transformation but the transformation result is discarded.
I'll try #325 and report back in the nearest future.

**Comment by phlptp** [comment] 2019-10-08 12:28
I am going to add the code you posted(unless you object) to a test case and make sure it passes.

**Comment by jzakrzewski** [comment] 2019-10-08 12:55
Yeah, go ahead. 
`cmd` is a pointer to `CLI::App` and `ExistingBehaviour` is an `enum class` if that's important.

BTW: I was positively surprised to see direct support for `enum class`.

**Comment by phlptp** [comment] 2019-10-08 14:15
The [test case](https://github.com/phlptp/CLI11/blob/f9baaeab88ced000b382c0956f2b70285119a51e/tests/TransformTest.cpp#L105-L120) is now passing in PR #325.  Had most of the pieces ready but needed to incorporate everything into the as function yet.    There is a few things to take care of on that PR yet before it is ready for merging with the main line, but it does pass all the tests.

**Comment by jzakrzewski** [comment] 2019-10-08 14:23
Nice!
Thanks for the quick reaction.

**Comment by jzakrzewski** [comment] 2019-10-08 18:04
Just to confirm - #325 works in a real codebase ;)

**Closed as completed** 2019-11-10 01:27 UTC
